using DataModelLib.Common;
using DataModelLib.Common.Schema;
using DataModelLib.Common.SourceGenerator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataViewModelLib.SourceGenerator
{
	public class DatabaseViewModelSourceGenerator : SourceGenerator<Database>
	{
		public override string GenerateSource(Database Database)
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			using System.Collections.Specialized;
			using System.Linq;
			using DataModelLib.Common;
			{{Database.Tables.Select(item => $"using {item.Namespace}.Models;").Distinct().Join()}}

			namespace {{Database.Namespace}}.ViewModels
			{
				public partial class {{Database.DatabaseName}}ViewModel
				{
					private {{Database.DatabaseName}}Model dataSource;

			{{Database.Tables.Select(item=> GenerateProperties(Database,item)).Join().Indent(2)}}

					public {{Database.DatabaseName}}ViewModel({{Database.DatabaseName}}Model DataSource)
					{
						this.dataSource=DataSource;
			{{Database.Tables.Select(item => $"{item.TableName}ViewModelCollection = new {item.TableName}ViewModelCollection(dataSource);").Join().Indent(3)}}
					}
						
				}
			}
			""";

			return source;
		}

		private string GenerateProperties(Database Database,Table Table)
		{
			string source =
			$$"""
			public {{Table.TableName}}ViewModelCollection {{Table.TableName}}ViewModelCollection
			{
				get;
				private set;
			}
			""";
			return source;
		}




	}
	
}
