using DataModelLib.Common;
using DataModelLib.Common.Schema;
using DataModelLib.Common.SourceGenerator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataViewModelLib.SourceGenerator
{
	public class DatabaseViewModelSourceGenerator : SourceGenerator<Database>
	{
		public override string GenerateSource(Database Database)
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			using System.Collections.Specialized;
			using System.Linq;
			using DataModelGenerator;
			{{Database.Tables.Select(item => $"using {item.Namespace};").Distinct().Join()}}

			namespace {{Database.Namespace}}
			{
				public partial class {{Database.DatabaseName}}ViewModel
				{
					private {{Database.DatabaseName}}Model dataSource;

					public {{Database.DatabaseName}}ViewModel({{Database.DatabaseName}}Model DataSource)
					{
						this.dataSource=DataSource;
					}
						
				}
			}
			""";

			return source;
		}

	}
}
