using DataModelLib.Common;
using DataModelLib.Common.Schema;
using DataModelLib.Common.SourceGenerator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataViewModelLib.SourceGenerator
{
	public class TableViewModelSourceGenerator : SourceGenerator<Table>
	{
		public override string GenerateSource(Table Table)
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			using System.Linq;
			using System.ComponentModel;
			using System.Windows;
			using DataModelLib.Common;
			using {{Table.Namespace}}.Models;			
			
			namespace {{Table.Namespace}}.ViewModels
			{
				public partial class {{Table.TableName}}ViewModel : DependencyObject
				{

					private {{Table.TableName}}Model dataSource
					{
						get;
						set;
					}

					private {{Table.DatabaseName}}ViewModel databaseViewModel;
					
					public {{Table.TableName}}ViewModel({{Table.DatabaseName}}ViewModel DatabaseViewModel,{{Table.TableName}}Model DataSource)
					{
						this.databaseViewModel=DatabaseViewModel; this.dataSource=DataSource;
					}
			
				}
			}
			""";

			return source;
		}

	}
}
