using DataModelLib.Common;
using DataModelLib.Common.Schema;
using DataModelLib.Common.SourceGenerator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataViewModelLib.SourceGenerator
{
	public class ViewModelSourceGenerator : SourceGenerator<Table>
	{
		public override string GenerateSource(Table Table)
		{
			string source =
			$$"""
			// <auto-generated/>
			using System;
			using System.Collections.Generic;
			using System.Linq;
			using System.ComponentModel;
			using System.Windows;
			using DataModelLib.Common;
			using {{Table.Namespace}}.Models;			
						
			namespace {{Table.Namespace}}.ViewModels
			{
				public partial class {{Table.TableName}}ViewModel : IViewModel, INotifyPropertyChanged
				{
					#nullable enable
					public event PropertyChangedEventHandler? PropertyChanged;
					#nullable disable
			
					private {{Table.TableName}}Model dataSource
					{
						get;
						set;
					}

					private {{Table.DatabaseName}}Model databaseModel;
					private {{Table.DatabaseName}}ViewModel databaseViewModel;
						
			{{Table.Columns.Select(item => GenerateProperty(item)).Join().Indent(2)}}
			{{Table.Relations.Select(item => GenerateProperty(Table, item)).Join().Indent(2)}}
			
					public {{Table.TableName}}ViewModel({{Table.DatabaseName}}ViewModel DatabaseViewModel, {{Table.DatabaseName}}Model DatabaseModel, {{Table.TableName}}Model DataSource)
					{
						this.databaseModel=DatabaseModel; 
						this.databaseViewModel=DatabaseViewModel; 
						this.dataSource=DataSource;

						{{Table.Relations.Where(item => item.PrimaryTable == Table).Select(item => $"_{item.PrimaryPropertyName} = new {item.PrimaryPropertyName}ViewModelCollection(databaseViewModel, databaseModel, dataSource);").Join().Indent(3)}}
									
						DataSource.PropertyChanged += OnModelPropertyChanged;
					}

					private void OnModelPropertyChanged(object sender, PropertyChangedEventArgs e)
					{
						OnPropertyChanged(e.PropertyName);
					}

					protected virtual void OnPropertyChanged(string PropertyName)
					{
						if (PropertyChanged!=null) PropertyChanged(this, new PropertyChangedEventArgs(PropertyName));
					}
			
					public void Delete()
					{
						this.databaseModel.Remove{{Table.TableName}}(dataSource);
					}
					public override string ToString()
					{
						return dataSource.ToString();
					}
				}
			}
			""";

			return source;
		}

		private string GenerateProperty(Column Column)
		{
			string source =
			$$"""
			public {{Column.TypeName}} {{Column.ColumnName}}
			{
				get { return dataSource.{{Column.ColumnName}}; }
				set { dataSource.{{Column.ColumnName}} = value; }
			}
			""";
			return source;
		}
		private string GenerateProperty(Table Table, Relation Relation)
		{
			string source;
			if (Relation.ForeignTable == Table) return "";
			
			source =
			$$"""
			private {{Relation.PrimaryPropertyName}}ViewModelCollection _{{Relation.PrimaryPropertyName}};
			public {{Relation.PrimaryPropertyName}}ViewModelCollection {{Relation.PrimaryPropertyName}}
			{
				get { return this._{{Relation.PrimaryPropertyName}}; }
			}
			""";
			return source;
		}


	}
}
